bolgeler: marmara karadeniz ege
	cat marmara karadeniz ege | sort -u > bolgeler

marmara: istanbul bursa
	cat istanbul bursa | sort -u > marmara

karadeniz: samsun sinop
	cat samsun sinop | sort -u > karadeniz

ege: izmir aydin
	cat izmir aydin | sort -u > ege

clean:
	rm -f ege karadeniz marmara bolgeler
